sudo: required
dist: trusty

os: linux
language: cpp
compiler: gcc

env:
  global:
    - OPENSSL_VERSION=1.0.2k

matrix:
  fast_finish: true
  include:
    - compiler: ": Win32"
      env: CHOST=i686-w64-mingw32 CONFIG=""
    - compiler: ": Win64"
      env: CHOST=x86_64-w64-mingw32 CONFIG=""
    - compiler: ": Win32"
      env: CHOST=i686-w64-mingw32 CONFIG="--disable-password-change"
    - compiler: ": Win64"
      env: CHOST=x86_64-w64-mingw32 CONFIG="--disable-password-change"
  exclude:
    - compiler: gcc

addons:
  apt:
    packages:
      - gcc-mingw-w64
      - cppcheck

before_script:
    - unset CC; unset CXX

script:
    - cppcheck --force --enable=warning,missingInclude --error-exitcode=1 . >build.log 2>&1 || (cat build.log && exit 1)
    - if [[ $CONFIG != *"--disable-password-change"* ]]; then . .travis-build-openssl.sh; fi
    - autoreconf -i -v
    - ./configure --prefix=/ --libdir=/lib --host=$CHOST --build=x86_64-pc-linux-gnu --program-prefix='' $CONFIG && make
# build from tarball
    - make distdir=dist dist && tar xvf dist.tar.gz && cd dist
    - ./configure --prefix=/ --libdir=/lib --host=$CHOST --build=x86_64-pc-linux-gnu --program-prefix='' $CONFIG && make
    
cache:
  directories:
  - download-cache

